"""S6 - font fix: make a game able to draw Chinese, before anything else runs.

Why this is separate from the translate pipeline: a game that renders Chinese
as tofu (empty boxes) has a font problem, not a translation problem. Every
Chinese string - whether it came from a tl/ block or from an external tool
injecting text into the game's own text box at runtime - is drawn by the game's
engine with whatever font the current style names. If that face has no Hanzi,
the text cannot appear. Fixing the font once makes all of those paths work.

Two modes, and they must not be mixed on one install:

  luna  Fonts only. Nothing about language or tl/ is touched, so the game keeps
        showing its own text and an external translator is free to swap the
        text in at runtime. This is the pre-flight mode.

  full  Fonts plus `config.language`, for when rpykit itself installed a
        translation and the game should start in Chinese.

Installing both would make the game render rpykit's Chinese first and then have
the external tool translate that Chinese into Chinese again.

Nothing here edits a game script or repacks an archive. Every write is
recorded in install_manifest.json and undone by `rpykit-luna --revert`.
"""

import datetime
import os
import re
import shutil
import string
import sys

import fontdb
import fontscan
import proj

HERE = os.path.dirname(os.path.abspath(__file__))


def _asset(name):
    """A bundled data file, both from source and from a frozen build.

    A one-file build extracts itself to sys._MEIPASS and points __file__ in
    there, so resolving assets from HERE alone would lose the font exactly
    when the tool is shipped.
    """
    return os.path.join(getattr(sys, "_MEIPASS", None) or HERE, "assets", name)


ASSET_FONT = _asset("NotoSansSC-VF.ttf")

GAME_FONT_REL = "localization/NotoSansSC-VF.ttf"
SHIM_REL = "zz_localization.rpy"

# Ren'Py's stock defaults. Every gui.rpy defines gui.text_font and friends from
# these names, so they are aliased even when a scan misses the literal.
BASELINE_FACES = ["DejaVuSans.ttf", "DejaVuSans-Bold.ttf"]

# Ren'Py draws emoji and the accessibility font through their own mechanisms,
# so aliasing these would break features rather than fix them. Matched on the
# lowercased stem, because the extension-less safety net below also produces
# names like "TwemojiCOLRv0" that must be caught by the same rule.
NEVER_ALIAS_STEMS = {"twemojicolrv0", "_opendyslexic3-regular"}

LATIN_FULL = (0x0000, 0x2E7F)
LATIN_ASCII = (0x0020, 0x007E)

SHIM = string.Template('''\
########################################################################
# zz_localization.rpy - font glue for Chinese text
#
# GENERATED BY `rpykit fontfix` - do not hand-edit, it will be regenerated.
# Undo with:  rpykit-luna --revert
#
# Non-destructive. This file only ADDS behaviour on top of the shipped game;
# it never edits a game script and never repacks an archive.
#
# The faces this game ships contain no CJK Hanzi, so Chinese drawn with them
# comes out as tofu (the empty-box characters). Each font name the game
# resolves is pointed at a FontGroup that keeps the original face for Latin
# and hands everything CJK to the font installed alongside this file.
#
# Generated: $stamp
# Game:      $game_dir
# Mode:      $mode
$table_comment
########################################################################

init 999 python:
$language_block
    # Ren'Py searches "localization/..." with the loader prefixes ["", "fonts/"]
    # (renpy/text/font.py:648), so this resolves next to this rpy file.
    _loc_cjk = "$cjk_path"

    def _loc_group(latin_face, lo, hi):
        """A FontGroup: `latin_face` for one Latin range, Noto for CJK.

        A FontGroup is not a font file. Ren'Py splits each rendered string by
        codepoint and draws each run with whichever font claims it, and the
        first add() to claim a codepoint wins - so ranges are added
        narrowest-first and the bare (None, None) default goes last.

        `latin_face` is None when the original face does not have complete
        Latin coverage. Delegating a range to a face that cannot fill it
        produces blanks, which is worse than losing the styling.

        Note the signature of FontGroup.add: end is a required positional and
        is ignored only when start is None. Passing two arguments raises
        `TypeError: add() missing 1 required positional argument: 'end'`.
        """
        group = FontGroup()

        if latin_face:
            group.add(latin_face, lo, hi)

        group.add(_loc_cjk, 0x3000, 0x30FF)     # CJK punctuation, kana
        group.add(_loc_cjk, 0x3400, 0x4DBF)     # CJK Extension A
        group.add(_loc_cjk, 0x4E00, 0x9FFF)     # CJK Unified Ideographs
        group.add(_loc_cjk, 0xF900, 0xFAFF)     # CJK Compatibility Ideographs
        group.add(_loc_cjk, 0xFE10, 0xFE4F)     # CJK Compatibility Forms
        group.add(_loc_cjk, 0xFF00, 0xFFEF)     # Halfwidth and Fullwidth Forms
        group.add(_loc_cjk, 0x20000, 0x2FA1F)   # CJK Extensions B onwards
        group.add(_loc_cjk, None, None)         # default for everything else

        return group

    # (alias, delegating Latin face or None, delegate from, delegate to)
    _loc_faces = [
$faces
    ]

    # Pass 1 builds every group before anything is aliased, because
    # FontGroup.add() refuses a face whose name is already a registered alias.
    # Aliasing during the build would break the second name delegating to the
    # first. Groups are memoised on the delegation config so that names which
    # resolve to the same face share one object: a group materialises a
    # codepoint entry per covered character, so one per name would be several
    # megabytes each.
    _loc_cache = {}
    _loc_built = []
    for _loc_name, _loc_latin, _loc_lo, _loc_hi in _loc_faces:
        _loc_key = (_loc_latin, _loc_lo, _loc_hi)
        if _loc_key not in _loc_cache:
            try:
                _loc_cache[_loc_key] = _loc_group(_loc_latin, _loc_lo, _loc_hi)
            except Exception:
                # Either the game already aliased this name or the face cannot
                # be loaded. Noto-only still renders Chinese; it just drops the
                # original styling, which beats an init-time crash on startup.
                _loc_cache[_loc_key] = _loc_group(None, 0, 0)
        _loc_built.append((_loc_name, _loc_cache[_loc_key]))

    # Pass 2 publishes them. config.font_name_map is consulted wherever a font
    # *name* is resolved: style definitions, style inheritance and inline
    # {font=...} tags (renpy/text/text.py lines 254, 296 and 1395). That covers
    # every font the game hardcodes, including ones baked into dialogue.
    for _loc_name, _loc_group_obj in _loc_built:
        config.font_name_map[_loc_name] = _loc_group_obj
''')

LANGUAGE_BLOCK = '''
    # config.language is read by renpy/common/00start.rpy:_init_language() on
    # every launch, which makes it an unconditional override. Its sibling
    # config.default_language is only consulted the first time the game runs
    # (renpy/common/00defaults.rpy, init 1500), so it would do nothing on an
    # install that has already been started once.
    config.language = "$lang"
'''


class FontFixError(Exception):
    pass


def _stem(name):
    """The file name without its extension, casing preserved.

    Ren'Py resolves `font "MyFont"` by retrying the name with each known font
    extension appended, so the extension-less spelling has to be aliased with
    the game's own casing, not a normalised one.
    """
    return os.path.splitext(fontscan.basename(name))[0]


def _is_engine_font(name):
    return _stem(name).lower() in NEVER_ALIAS_STEMS


MARKER = "GENERATED BY `rpykit fontfix`"


def _is_ours(path):
    """True if `path` is a file this tool wrote.

    Lets a re-run overwrite its own output even when the manifest is missing -
    a different machine, a moved exe, a wiped %LOCALAPPDATA% - instead of
    failing on "already exists". The shim is text and carries a marker in its
    header; the font is binary, so it is identified by being byte-identical to
    the bundled asset. Anything else is the player's own file and is still
    refused.
    """
    try:
        if path.lower().endswith((".ttf", ".otf")):
            if not os.path.isfile(ASSET_FONT):
                return False
            if os.path.getsize(path) != os.path.getsize(ASSET_FONT):
                return False
            with open(path, "rb") as a, open(ASSET_FONT, "rb") as b:
                while True:
                    chunk_a, chunk_b = a.read(1 << 20), b.read(1 << 20)
                    if chunk_a != chunk_b:
                        return False
                    if not chunk_a:
                        return True
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return MARKER in f.read(2048)
    except OSError:
        return False


def installed_state(game_dir):
    """What this tool has already put into `game_dir`.

    `current` is False for a shim written by an older build of this tool, so a
    caller can offer to reinstall rather than reporting a stale install as
    fine. The template marker is what distinguishes them; the header stamp
    cannot, since it changes on every write.
    """
    gdir = os.path.join(game_dir, "game")
    shim = os.path.join(gdir, SHIM_REL)
    state = {"shim": os.path.isfile(shim),
             "font": os.path.isfile(os.path.join(gdir, *GAME_FONT_REL.split("/"))),
             "ours": False, "mode": None, "current": False}
    if not state["shim"]:
        return state
    state["ours"] = _is_ours(shim)
    if not state["ours"]:
        return state
    try:
        with open(shim, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return state
    m = re.search(r"^# Mode:\s*(\S+)", text, re.M)
    if m:
        state["mode"] = m.group(1)
    state["current"] = "_loc_group(" in text
    return state


def _archive_paths(game_dir):
    gdir = os.path.join(game_dir, "game")
    if not os.path.isdir(gdir):
        return []
    return [os.path.join(gdir, n) for n in sorted(os.listdir(gdir))
            if n.lower().endswith(".rpa") and os.path.isfile(os.path.join(gdir, n))]


def _resolve(ref, inventory):
    """(bytes, inventory entry) for the face `ref` names, or (None, None).

    Tried the way Ren'Py itself resolves a font: the reference as written, its
    basename, then that basename with each known font extension appended. The
    inventory is keyed by basename, so `fonts/tycho.ttf` finds
    `game/fonts/tycho.ttf` without knowing the layout. A miss is not fatal -
    it just means the face cannot be measured, and an unmeasurable face is
    never delegated Latin.
    """
    stem = os.path.splitext(fontscan.basename(ref))[0]
    cands = [ref, fontscan.basename(ref)] + [stem + e for e in fontscan.FONT_EXTS]
    for c in cands:
        entry = inventory.get(c)
        if entry is None:
            for name, e in inventory.items():
                if name.lower() == c.lower():
                    entry = e
                    break
        if entry is not None:
            data = fontscan.font_bytes(entry)
            if data:
                return data, entry
    return None, None


def analyse(game_dir):
    """Decide, per face, which font names to alias and what to delegate.

    Decisions are grouped by the face a name resolves to, so `Dongle-Bold` and
    `Dongle-Bold.ttf` share one decision - and one FontGroup. That matters:
    building a FontGroup materialises a codepoint entry per covered character,
    roughly 100k dict entries, so one group per *name* costs ~7 MB and a game
    shipping twenty fonts would pay 150 MB for maps it never reads.
    """
    report = fontscan.recon(game_dir, _archive_paths(game_dir))
    inventory = report["inventory"]

    # name -> why we are considering it. A name the game actually uses gets
    # measured. A font that merely happens to be shipped is only a safety net
    # for references this scan could not see, and it is served by the shared
    # Noto-only group, so it costs nothing worth counting.
    wanted = {}
    for ref in report["refs"]:
        wanted[ref] = "script literal"
    for base in BASELINE_FACES:
        wanted.setdefault(base, "renpy default")
    for name, entry in inventory.items():
        if entry["where"] == "renpy-common":
            # The engine's own faces. Twemoji and OpenDyslexic back features
            # that aliasing would break, and the rest are not the game's.
            continue
        if name == os.path.basename(GAME_FONT_REL):
            continue
        wanted.setdefault(name, "shipped file")
        wanted.setdefault(_stem(name), "shipped file")

    by_face = {}
    loose = []
    for name in sorted(wanted, key=lambda s: (s.lower(), s)):
        if _is_engine_font(name):
            loose.append((name, "engine feature font", None))
            continue
        data, entry = _resolve(name, inventory)
        if entry is None:
            loose.append((name, "face not found; cannot measure coverage", data))
            continue
        canon = fontscan.basename(entry.get("path") or entry["entry"])
        rec = by_face.setdefault(canon, {
            "names": set(), "reasons": set(), "entry": entry, "data": data})
        rec["names"].add(name)
        rec["reasons"].add(wanted[name])

    decisions = []
    for canon in sorted(by_face, key=str.lower):
        rec = by_face[canon]
        names = sorted(rec["names"], key=lambda s: (s.lower(), s))
        where = rec["entry"]["where"]

        if rec["reasons"] == {"shipped file"}:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "shipped but never named; safety net only",
                              "where": where})
            continue

        data = rec["data"]
        if data is None:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "face unreadable", "where": where})
            continue
        try:
            cps = fontdb.codepoints(data)
        except ValueError as e:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "unreadable face: %s" % e, "where": where})
            continue

        cjk = fontdb.cjk_count(cps)
        if cjk >= fontdb.CJK_FONT_THRESHOLD:
            decisions.append({"names": names, "action": "skip", "cjk": cjk,
                              "why": "already covers Hanzi", "where": where})
        elif fontdb.latin_complete(cps):
            decisions.append({"names": names, "action": "keep-latin", "cjk": cjk,
                              "latin": canon, "lo": LATIN_FULL[0], "hi": LATIN_FULL[1],
                              "why": "Latin complete", "where": where})
        elif all(c in cps for c in range(LATIN_ASCII[0], LATIN_ASCII[1] + 1)):
            decisions.append({"names": names, "action": "keep-ascii", "cjk": cjk,
                              "latin": canon, "lo": LATIN_ASCII[0], "hi": LATIN_ASCII[1],
                              "why": "ASCII complete only", "where": where})
        else:
            decisions.append({"names": names, "action": "noto-only", "cjk": cjk,
                              "why": "Latin coverage incomplete", "where": where})

    for name, why, _data in loose:
        decisions.append({"names": [name], "action": "noto-only", "cjk": None,
                          "why": why, "where": None})

    decisions.sort(key=lambda d: (d["action"], d["names"][0].lower()))
    return report, decisions


def _faces_block(decisions):
    rows = []
    for d in decisions:
        if d["action"] == "skip":
            continue
        latin = _q(d["latin"]) if d.get("latin") else "None"
        lo = "0x%04X" % d["lo"] if d.get("latin") else "0"
        hi = "0x%04X" % d["hi"] if d.get("latin") else "0"
        for name in d["names"]:
            rows.append("        (%s, %s, %s, %s)," % (_q(name), latin, lo, hi))
    return "\n".join(rows) if rows else "        # (nothing to alias)"


def _q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _table_comment(decisions):
    vf = {"keep-latin": "KEEP-LATIN", "keep-ascii": "KEEP-ASCII",
          "noto-only": "NOTO-ONLY", "skip": "SKIP"}
    lines = ["#", "# Decision table (from the .rpyc/.rpa scan of this game):"]
    for d in decisions:
        cjk = "" if d.get("cjk") is None else "cjk %5d  " % d["cjk"]
        where = d.get("where") or "-"
        names = ", ".join(d["names"])
        lines.append("#   %-11s %-36s %s%s" % (vf[d["action"]], names[:36], cjk, where))
        if len(names) > 36:
            lines.append("#   %-11s %s" % ("", names[36:]))
    return "\n".join(lines) + "\n"


def _code_only(text):
    """Drop comments and docstrings so a check sees code, not prose.

    The shim documents the very call signature being checked, so scanning raw
    text would flag its own explanatory comment.
    """
    text = re.sub(r'""".*?"""', '""', text, flags=re.S)
    return "\n".join(line.split("#", 1)[0] for line in text.splitlines())


def validate_shim(text):
    """Catch the failure mode that costs a startup crash.

    FontGroup.add takes (font, start, end); end has no default. A two-argument
    call raises TypeError at init 999, which the player sees as the game not
    starting at all. Counting arguments here is cheaper than discovering it in
    a playtest.
    """
    code = _code_only(text)
    problems = []
    for m in re.finditer(r"\.add\(([^()]*)\)", code):
        args = [a for a in m.group(1).split(",") if a.strip()]
        if len(args) < 3:
            problems.append("FontGroup.add called with %d argument(s): %s"
                            % (len(args), m.group(0)))
    if "config.font_name_map[" not in code:
        problems.append("no config.font_name_map assignment")
    if "FontGroup()" not in code:
        problems.append("no FontGroup constructed")

    # The body of `init 999 python:` is plain Python, so it can be compiled
    # here without booting the engine. Names like FontGroup and config are
    # undefined at this point, which is fine - compile() checks syntax only.
    # This is what catches a generated font name that broke its own quoting.
    body = []
    inside = False
    for line in text.splitlines():
        if line.startswith("init 999 python:"):
            inside = True
            continue
        if inside:
            if not line.strip():
                body.append("")
            elif line.startswith("    "):
                body.append(line[4:])
            else:
                break
    if not body:
        problems.append("no init 999 python: block found")
    else:
        try:
            compile("\n".join(body), "<zz_localization>", "exec")
        except SyntaxError as e:
            problems.append("python block does not compile: line %s: %s" % (e.lineno, e.msg))
    return problems


def _write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    tmp = path + ".part"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)


def install(args, game_dir, work, decisions):
    gdir = os.path.join(game_dir, "game")
    shim_path = os.path.join(gdir, SHIM_REL)
    font_path = os.path.join(gdir, *GAME_FONT_REL.split("/"))

    manifest = proj.load_manifest(work)
    ours = {e["path"] for e in manifest.get("files", [])}

    for rel in ("game/" + SHIM_REL, "game/" + GAME_FONT_REL):
        full = os.path.join(game_dir, *rel.split("/"))
        if not os.path.exists(full) or rel in ours or _is_ours(full):
            continue
        if not args.force:
            raise FontFixError(
                "%s already exists and was not installed by rpykit-luna.\n"
                "  pass --force to quarantine the leftover and continue." % rel)
        qdir = proj.ensure_dir(os.path.join(work, "quarantine"))
        dest = os.path.join(qdir, os.path.basename(rel))
        shutil.copy2(full, dest)
        print("[S6] quarantine: %s -> quarantine/%s" % (rel, os.path.basename(rel)))

    lang_block = ""
    if args.mode == "full":
        lang_block = string.Template(LANGUAGE_BLOCK).substitute(lang=args.lang)

    text = SHIM.substitute(
        stamp=datetime.datetime.now().isoformat(timespec="seconds"),
        game_dir=game_dir,
        mode=args.mode,
        cjk_path=GAME_FONT_REL,
        faces=_faces_block(decisions),
        language_block=lang_block,
        table_comment=_table_comment(decisions),
    )

    # Validate before anything reaches disk, so a self-check failure leaves no
    # half-installed state behind.
    problems = validate_shim(text)
    if problems:
        for p in problems:
            print("[S6] !! %s" % p)
        raise FontFixError("generated shim failed self-check; nothing written")

    if args.dry_run:
        print("[S6] dry-run: would write game/%s (%.1f MB)"
              % (GAME_FONT_REL, os.path.getsize(ASSET_FONT) / 1e6))
        print("[S6] dry-run: would write game/%s (%d lines, self-check clean)"
              % (SHIM_REL, text.count("\n")))
        return

    os.makedirs(os.path.dirname(font_path), exist_ok=True)
    shutil.copy2(ASSET_FONT, font_path)
    proj.record_file(work, game_dir, "game/" + GAME_FONT_REL, "fontfix:cjk-font")
    print("[S6] wrote  : game/%s (%.1f MB)" % (GAME_FONT_REL, os.path.getsize(font_path) / 1e6))

    _write(shim_path, text)
    proj.record_file(work, game_dir, "game/" + SHIM_REL, "fontfix:shim")
    n_alias = sum(len(d["names"]) for d in decisions if d["action"] != "skip")
    n_groups = len({(d.get("latin"), d.get("lo"), d.get("hi"))
                    for d in decisions if d["action"] != "skip"})
    print("[S6] wrote  : game/%s (%d aliases over %d FontGroup(s), self-check clean)"
          % (SHIM_REL, n_alias, n_groups))


def revert(game_dir, work):
    gdir = os.path.join(game_dir, "game")
    manifest = proj.load_manifest(work)

    removed = []
    for rel in ("game/" + SHIM_REL, "game/" + SHIM_REL + "c",
                "game/" + GAME_FONT_REL):
        full = os.path.join(game_dir, *rel.split("/"))
        if os.path.isfile(full):
            os.remove(full)
            removed.append(rel)

    locdir = os.path.join(gdir, "localization")
    if os.path.isdir(locdir) and not os.listdir(locdir):
        os.rmdir(locdir)
        removed.append("game/localization/")

    manifest["files"] = [e for e in manifest.get("files", [])
                         if not e.get("source", "").startswith("fontfix:")]
    proj.save_manifest(work, manifest)

    for rel in removed:
        print("[S6] removed: %s" % rel)
    if not removed:
        print("[S6] nothing to remove")
    print("[S6] reverted")


def run(args):
    if args.game_dir:
        game_dir = os.path.abspath(args.game_dir)
    else:
        from_proj = proj.load_project(args.work)
        game_dir = from_proj["game_dir"]
    if not os.path.isdir(os.path.join(game_dir, "game")):
        raise SystemExit("no game/ subdir - is this a Ren'Py distribution? %s" % game_dir)

    work = proj.ensure_dir(args.work or proj.work_dir_for(game_dir))

    print("[S6] game   : %s" % game_dir)
    if args.revert:
        revert(game_dir, work)
        return 0

    if args.mode not in ("luna", "full"):
        raise SystemExit("--mode must be luna or full")

    print("[S6] work   : %s" % work)
    print("[S6] mode   : %s%s" % (
        args.mode,
        " - fonts only; language and tl/ untouched (for runtime text injection)"
        if args.mode == "luna" else " - fonts + config.language"))

    before = installed_state(game_dir)
    if before["ours"]:
        print("[S6] state  : already installed (mode %s, %s); overwriting in place"
              % (before["mode"] or "?", "current template" if before["current"]
                 else "OLDER template"))

    report, decisions = analyse(game_dir)

    n_refs = len(report["refs"])
    print("[S6] scan   : %d font reference(s) in scripts, %d font file(s) shipped"
          % (n_refs, len(report["inventory"])))
    print("[S6] faces  :")
    for d in decisions:
        cjk = "--" if d.get("cjk") is None else "%d" % d["cjk"]
        names = ", ".join(d["names"])
        print("      %-11s %-38s cjk %5s  %s"
              % (d["action"], names[:38], cjk, d["why"]))

    aliased = [d for d in decisions if d["action"] != "skip"]
    if not aliased:
        print("[S6] every face already covers Chinese; nothing to do")
        return 0

    install(args, game_dir, work, decisions)

    proj.write_json(os.path.join(work, "fontfix_report.json"), {
        "game_dir": game_dir,
        "mode": args.mode,
        "installed": not args.dry_run,
        "cjk_font": GAME_FONT_REL,
        "shim": "game/" + SHIM_REL,
        "decisions": decisions,
        "refs": report["refs"],
    })

    print("[S6] OK - start the game to verify; `rpykit-luna --revert` undoes it")
    return 0
