"""What rpykit-luna installs into a Ren'Py game, and the runner that does it.

The tool applies one or more *features* to a game folder, each an independent
change with its own generated file and its own undo. The catalogue lives in
features.py; this module implements them and runs them. There are two today:

  fontfix  `zz_localization.rpy` points every font name the game resolves at a
           FontGroup that keeps the original face for Latin and draws CJK with
           the bundled Noto, plus the font itself under game/localization/.
           A game that renders Chinese as tofu (empty boxes) has a font
           problem, not a translation problem - and every Chinese string,
           whether from a tl/ block or injected into the text box at runtime by
           an external translator, is drawn with whatever font the current
           style names. Fixing the font once makes all of those paths work.
           This is why it is a pre-flight step and not part of translating.

  intro    `zz_rpykit_intro.rpy` points the game's `splashscreen` label at a
           no-op, so the opening logos stop being part of every launch. It is a
           separate file from the shim because it is a different class of
           change - the shim only ADDS aliases, while this one displaces a
           label the game defines - and because it has to be revertible alone.

Two modes, and they must not be mixed on one install:

  luna  Fonts only. Nothing about language or tl/ is touched, so the game keeps
        showing its own text and an external translator is free to swap the
        text in at runtime. This is the pre-flight mode.

  full  Fonts plus `config.language`, for when rpykit itself installed a
        translation and the game should start in Chinese.

Installing both would make the game render rpykit's Chinese first and then have
the external tool translate that Chinese into Chinese again.

Nothing here edits a game script or repacks an archive. Every write is
recorded in install_manifest.json and undone by `rpykit-luna --revert`.
"""

import datetime
import os
import re
import shutil
import string
import sys

import compat
import features
import fontdb
import fontscan
import proj

HERE = os.path.dirname(os.path.abspath(__file__))


def _asset(name):
    """A bundled data file, both from source and from a frozen build.

    A one-file build extracts itself to sys._MEIPASS and points __file__ in
    there, so resolving assets from HERE alone would lose the font exactly
    when the tool is shipped.
    """
    return os.path.join(getattr(sys, "_MEIPASS", None) or HERE, "assets", name)


ASSET_FONT = _asset("NotoSansSC-VF.ttf")

GAME_FONT_REL = "localization/NotoSansSC-VF.ttf"
SHIM_REL = "zz_localization.rpy"

# The second generated file: a label override that skips the opening logos.
# Kept separate from the shim so the two can be installed and reverted on their
# own - the shim only ever ADDS to the game, while this one replaces a label the
# game defines, which is a different class of change to be able to undo.
INTRO_REL = "zz_rpykit_intro.rpy"
INTRO_LABEL = "zz_rpykit_intro"

# Manifest source for a rival override this tool moved aside to make room for
# the intro, and the only quarantine `--revert` puts back.
QUARANTINE_INTRO = "fontfix:intro-conflict"

# Ren'Py's stock defaults. Every gui.rpy defines gui.text_font and friends from
# these names, so they are aliased even when a scan misses the literal.
BASELINE_FACES = ["DejaVuSans.ttf", "DejaVuSans-Bold.ttf"]

# Ren'Py draws emoji and the accessibility font through their own mechanisms,
# so aliasing these would break features rather than fix them. Matched on the
# lowercased stem, because the extension-less safety net below also produces
# names like "TwemojiCOLRv0" that must be caught by the same rule.
NEVER_ALIAS_STEMS = {"twemojicolrv0", "_opendyslexic3-regular"}

LATIN_FULL = (0x0000, 0x2E7F)
LATIN_ASCII = (0x0020, 0x007E)

SHIM = string.Template('''\
########################################################################
# zz_localization.rpy - font glue for Chinese text
#
# GENERATED BY `rpykit fontfix` - do not hand-edit, it will be regenerated.
# Undo with:  rpykit-luna --revert
#
# Non-destructive. This file only ADDS behaviour on top of the shipped game;
# it never edits a game script and never repacks an archive.
#
# The faces this game ships contain no CJK Hanzi, so Chinese drawn with them
# comes out as tofu (the empty-box characters). Each font name the game
# resolves is pointed at a FontGroup that keeps the original face for Latin
# and hands everything CJK to the font installed alongside this file.
#
# Generated: $stamp
# Game:      $game_dir
# Mode:      $mode
$table_comment
########################################################################

init 999 python:
$language_block
    # Ren'Py searches "localization/..." with the loader prefixes ["", "fonts/"]
    # (renpy/text/font.py:648), so this resolves next to this rpy file.
    _loc_cjk = "$cjk_path"

    def _loc_group(latin_face, lo, hi):
        """A FontGroup: `latin_face` for one Latin range, Noto for CJK.

        A FontGroup is not a font file. Ren'Py splits each rendered string by
        codepoint and draws each run with whichever font claims it, and the
        first add() to claim a codepoint wins - so ranges are added
        narrowest-first and the bare (None, None) default goes last.

        `latin_face` is None when the original face does not have complete
        Latin coverage. Delegating a range to a face that cannot fill it
        produces blanks, which is worse than losing the styling.

        Note the signature of FontGroup.add: end is a required positional and
        is ignored only when start is None. Passing two arguments raises
        `TypeError: add() missing 1 required positional argument: 'end'`.
        """
        group = FontGroup()

        if latin_face:
            group.add(latin_face, lo, hi)

        group.add(_loc_cjk, 0x3000, 0x30FF)     # CJK punctuation, kana
        group.add(_loc_cjk, 0x3400, 0x4DBF)     # CJK Extension A
        group.add(_loc_cjk, 0x4E00, 0x9FFF)     # CJK Unified Ideographs
        group.add(_loc_cjk, 0xF900, 0xFAFF)     # CJK Compatibility Ideographs
        group.add(_loc_cjk, 0xFE10, 0xFE4F)     # CJK Compatibility Forms
        group.add(_loc_cjk, 0xFF00, 0xFFEF)     # Halfwidth and Fullwidth Forms
        group.add(_loc_cjk, 0x20000, 0x2FA1F)   # CJK Extensions B onwards
        group.add(_loc_cjk, None, None)         # default for everything else

        return group

    # (alias, delegating Latin face or None, delegate from, delegate to)
    _loc_faces = [
$faces
    ]

    # Pass 1 builds every group before anything is aliased, because
    # FontGroup.add() refuses a face whose name is already a registered alias.
    # Aliasing during the build would break the second name delegating to the
    # first. Groups are memoised on the delegation config so that names which
    # resolve to the same face share one object: a group materialises a
    # codepoint entry per covered character, so one per name would be several
    # megabytes each.
    _loc_cache = {}
    _loc_built = []
    for _loc_name, _loc_latin, _loc_lo, _loc_hi in _loc_faces:
        _loc_key = (_loc_latin, _loc_lo, _loc_hi)
        if _loc_key not in _loc_cache:
            try:
                _loc_cache[_loc_key] = _loc_group(_loc_latin, _loc_lo, _loc_hi)
            except Exception:
                # Either the game already aliased this name or the face cannot
                # be loaded. Noto-only still renders Chinese; it just drops the
                # original styling, which beats an init-time crash on startup.
                _loc_cache[_loc_key] = _loc_group(None, 0, 0)
        _loc_built.append((_loc_name, _loc_cache[_loc_key]))

    # Pass 2 publishes them. config.font_name_map is consulted wherever a font
    # *name* is resolved: style definitions, style inheritance and inline
    # {font=...} tags (renpy/text/text.py lines 254, 296 and 1395). That covers
    # every font the game hardcodes, including ones baked into dialogue.
    for _loc_name, _loc_group_obj in _loc_built:
        config.font_name_map[_loc_name] = _loc_group_obj
''')

# No `$` may appear in the body of this template (string.Template.substitute
# would read it as a placeholder), and no font file name may appear anywhere in
# it: fontscan reads every loose .rpy in game/, so a stray ".ttf" here would be
# fed back in as though the game had referenced that face.
INTRO = string.Template('''\
########################################################################
# zz_rpykit_intro.rpy - go straight to the main menu
#
# GENERATED BY `rpykit fontfix` - do not hand-edit, it will be regenerated.
# Undo with:  rpykit-luna --revert
#
# Non-destructive. This file only ADDS behaviour on top of the shipped game;
# it never edits a game script and never repacks an archive.
#
# The game's own `splashscreen` label shows the opening logos, and on some
# builds its logo movie never returns, so the game looks hung before the main
# menu ever appears. This points that label at a no-op instead, so the engine
# falls straight through to the main menu.
#
# Why config.label_overrides rather than a second `label splashscreen:`: Ren'Py
# consults label_overrides from Script.lookup and Script.has_label
# (renpy/script.py), which is what the engine's `jump expression "splashscreen"`
# in renpy/common/00start.rpy goes through. Redefining a label the game already
# owns is only tolerated when developer mode is off; the override works either
# way.
#
# Why init 999: same-priority init blocks run in file-name order
# (renpy/script.py sort_script_files), so a plain `init python:` block in a
# hand-written zzz_* file would load after this one and win.
#
# The game's splashscreen no longer runs, so any store variable it used to set
# is not set. If the game fails at startup with a NameError, add the missing
# value under the label below. Its body must stay a single `return`:
# `_splashscreen` sets suppress_overlay, _confirm_quit and _autosave just before
# jumping here (renpy/common/00start.rpy), and it is the `return` that unwinds
# them.
#
# Not covered: Ren'Py draws the presplash images before any Python runs, so
# those still appear.
#
# Generated: $stamp
# Game:      $game_dir
########################################################################

init 999 python:
    config.label_overrides["splashscreen"] = "$intro_label"

label $intro_label:
    return
''')

LANGUAGE_BLOCK = '''
    # config.language is read by renpy/common/00start.rpy:_init_language() on
    # every launch, which makes it an unconditional override. Its sibling
    # config.default_language is only consulted the first time the game runs
    # (renpy/common/00defaults.rpy, init 1500), so it would do nothing on an
    # install that has already been started once.
    config.language = "$lang"
'''


class FontFixError(Exception):
    pass


def _stem(name):
    """The file name without its extension, casing preserved.

    Ren'Py resolves `font "MyFont"` by retrying the name with each known font
    extension appended, so the extension-less spelling has to be aliased with
    the game's own casing, not a normalised one.
    """
    return os.path.splitext(fontscan.basename(name))[0]


def _is_engine_font(name):
    return _stem(name).lower() in NEVER_ALIAS_STEMS


MARKER = "GENERATED BY `rpykit fontfix`"


def _is_ours(path):
    """True if `path` is a file this tool wrote.

    Lets a re-run overwrite its own output even when the manifest is missing -
    a different machine, a moved exe, a wiped %LOCALAPPDATA% - instead of
    failing on "already exists". The shim is text and carries a marker in its
    header; the font is binary, so it is identified by being byte-identical to
    the bundled asset. Anything else is the player's own file and is still
    refused.
    """
    try:
        if path.lower().endswith((".ttf", ".otf")):
            if not os.path.isfile(ASSET_FONT):
                return False
            if os.path.getsize(path) != os.path.getsize(ASSET_FONT):
                return False
            with open(path, "rb") as a, open(ASSET_FONT, "rb") as b:
                while True:
                    chunk_a, chunk_b = a.read(1 << 20), b.read(1 << 20)
                    if chunk_a != chunk_b:
                        return False
                    if not chunk_a:
                        return True
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return MARKER in f.read(2048)
    except OSError:
        return False


def _read_text(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return ""


def _font_state(game_dir):
    """What the font feature has already put into `game_dir`.

    `current` is False for a shim written by an older build of this tool, so a
    caller can offer to reinstall rather than reporting a stale install as
    fine. The template marker is what distinguishes them; the header stamp
    cannot, since it changes on every write.
    """
    gdir = os.path.join(game_dir, "game")
    shim = os.path.join(gdir, SHIM_REL)
    state = {"shim": os.path.isfile(shim),
             "font": os.path.isfile(os.path.join(gdir, *GAME_FONT_REL.split("/"))),
             "ours": False, "mode": None, "current": False}
    if not state["shim"]:
        return state
    state["ours"] = _is_ours(shim)
    if not state["ours"]:
        return state
    text = _read_text(shim)
    m = re.search(r"^# Mode:\s*(\S+)", text, re.M)
    if m:
        state["mode"] = m.group(1)
    state["current"] = "_loc_group(" in text
    return state


def _intro_state(game_dir):
    """What the intro feature has already put into `game_dir`."""
    intro = os.path.join(game_dir, "game", INTRO_REL)
    state = {"intro": os.path.isfile(intro),
             "intro_ours": False, "intro_current": False}
    if not state["intro"]:
        return state
    state["intro_ours"] = _is_ours(intro)
    if not state["intro_ours"]:
        return state
    state["intro_current"] = (
        'config.label_overrides["splashscreen"]' in _read_text(intro))
    return state


def installed_state(game_dir):
    """Everything this tool has already put into `game_dir`, feature by feature.

    A flat merge of the per-feature reports, so a caller keeps asking one
    question and gets the whole picture. The two features are merged rather
    than chained: they are installed by the same run but can be present
    separately, because a game that already had the shim from an older build
    has no intro yet, and a run with the intro ticked but the fonts unticked
    has the reverse.
    """
    state = {}
    for fid in features.ids():
        state.update(_FEATURES[fid].state(game_dir))
    return state


def _archive_paths(game_dir):
    gdir = os.path.join(game_dir, "game")
    if not os.path.isdir(gdir):
        return []
    return [os.path.join(gdir, n) for n in sorted(os.listdir(gdir))
            if n.lower().endswith(".rpa") and os.path.isfile(os.path.join(gdir, n))]


# An add-on file that redirects the splashscreen the same way this tool does.
# Deliberately narrow: it must touch config.label_overrides, because a game's
# own `label splashscreen:` is a completely normal thing to find (Supower and
# RiseOfTheCrimeLord both define one) and must never be mistaken for a rival
# add-on. The dictionary-literal form is checked separately because
# `label_overrides = {"splashscreen": ...}` has no bracket to anchor on.
_RE_OVERRIDE_SET = re.compile(
    r"""label_overrides\s*
        (?:\[\s*['"]splashscreen['"]\s*\]
          |\.\s*(?:update|setdefault)\s*\(\s*['"]splashscreen['"])""", re.X)
_RE_OVERRIDE_DICT = re.compile(r"label_overrides\s*=\s*\{")
_RE_OVERRIDE_KEY = re.compile(r"['\"]splashscreen['\"]\s*:")


def find_intro_conflicts(game_dir):
    """Loose .rpy files in game/ that already redirect the splashscreen.

    Scanned one level deep only, matching fontscan.script_blobs: game/tl/** is
    full of `translate ... splashscreen_<hash>:` blocks that would otherwise
    look like hits. .rpyc is not read - compiling strips the text this matches
    on - so a conflict with no .rpy beside it cannot be seen, which is why
    install() also handles the .rpyc of anything it moves.
    """
    gdir = os.path.join(game_dir, "game")
    if not os.path.isdir(gdir):
        return []
    out = []
    for name in sorted(os.listdir(gdir)):
        if not name.lower().endswith(".rpy"):
            continue
        path = os.path.join(gdir, name)
        if not os.path.isfile(path) or _is_ours(path):
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        code = _code_only(text)
        if _RE_OVERRIDE_SET.search(code) or (
                _RE_OVERRIDE_DICT.search(code) and _RE_OVERRIDE_KEY.search(code)):
            out.append(name)
    return out


def _resolve(ref, inventory):
    """(bytes, inventory entry) for the face `ref` names, or (None, None).

    Tried the way Ren'Py itself resolves a font: the reference as written, its
    basename, then that basename with each known font extension appended. The
    inventory is keyed by basename, so `fonts/tycho.ttf` finds
    `game/fonts/tycho.ttf` without knowing the layout. A miss is not fatal -
    it just means the face cannot be measured, and an unmeasurable face is
    never delegated Latin.
    """
    stem = os.path.splitext(fontscan.basename(ref))[0]
    cands = [ref, fontscan.basename(ref)] + [stem + e for e in fontscan.FONT_EXTS]
    for c in cands:
        entry = inventory.get(c)
        if entry is None:
            for name, e in inventory.items():
                if name.lower() == c.lower():
                    entry = e
                    break
        if entry is not None:
            data = fontscan.font_bytes(entry)
            if data:
                return data, entry
    return None, None


def analyse(game_dir):
    """Decide, per face, which font names to alias and what to delegate.

    Decisions are grouped by the face a name resolves to, so `Dongle-Bold` and
    `Dongle-Bold.ttf` share one decision - and one FontGroup. That matters:
    building a FontGroup materialises a codepoint entry per covered character,
    roughly 100k dict entries, so one group per *name* costs ~7 MB and a game
    shipping twenty fonts would pay 150 MB for maps it never reads.
    """
    report = fontscan.recon(game_dir, _archive_paths(game_dir))
    inventory = report["inventory"]

    # name -> why we are considering it. A name the game actually uses gets
    # measured. A font that merely happens to be shipped is only a safety net
    # for references this scan could not see, and it is served by the shared
    # Noto-only group, so it costs nothing worth counting.
    wanted = {}
    for ref in report["refs"]:
        wanted[ref] = "script literal"
    for base in BASELINE_FACES:
        wanted.setdefault(base, "renpy default")
    for name, entry in inventory.items():
        if entry["where"] == "renpy-common":
            # The engine's own faces. Twemoji and OpenDyslexic back features
            # that aliasing would break, and the rest are not the game's.
            continue
        if name == os.path.basename(GAME_FONT_REL):
            continue
        wanted.setdefault(name, "shipped file")
        wanted.setdefault(_stem(name), "shipped file")

    by_face = {}
    loose = []
    for name in sorted(wanted, key=lambda s: (s.lower(), s)):
        if _is_engine_font(name):
            loose.append((name, "engine feature font", None))
            continue
        data, entry = _resolve(name, inventory)
        if entry is None:
            loose.append((name, "face not found; cannot measure coverage", data))
            continue
        canon = fontscan.basename(entry.get("path") or entry["entry"])
        rec = by_face.setdefault(canon, {
            "names": set(), "reasons": set(), "entry": entry, "data": data})
        rec["names"].add(name)
        rec["reasons"].add(wanted[name])

    decisions = []
    for canon in sorted(by_face, key=str.lower):
        rec = by_face[canon]
        names = sorted(rec["names"], key=lambda s: (s.lower(), s))
        where = rec["entry"]["where"]

        if rec["reasons"] == {"shipped file"}:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "shipped but never named; safety net only",
                              "where": where})
            continue

        data = rec["data"]
        if data is None:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "face unreadable", "where": where})
            continue
        try:
            cps = fontdb.codepoints(data)
        except ValueError as e:
            decisions.append({"names": names, "action": "noto-only", "cjk": None,
                              "why": "unreadable face: %s" % e, "where": where})
            continue

        cjk = fontdb.cjk_count(cps)
        if cjk >= fontdb.CJK_FONT_THRESHOLD:
            decisions.append({"names": names, "action": "skip", "cjk": cjk,
                              "why": "already covers Hanzi", "where": where})
        elif fontdb.latin_complete(cps):
            decisions.append({"names": names, "action": "keep-latin", "cjk": cjk,
                              "latin": canon, "lo": LATIN_FULL[0], "hi": LATIN_FULL[1],
                              "why": "Latin complete", "where": where})
        elif all(c in cps for c in range(LATIN_ASCII[0], LATIN_ASCII[1] + 1)):
            decisions.append({"names": names, "action": "keep-ascii", "cjk": cjk,
                              "latin": canon, "lo": LATIN_ASCII[0], "hi": LATIN_ASCII[1],
                              "why": "ASCII complete only", "where": where})
        else:
            decisions.append({"names": names, "action": "noto-only", "cjk": cjk,
                              "why": "Latin coverage incomplete", "where": where})

    for name, why, _data in loose:
        decisions.append({"names": [name], "action": "noto-only", "cjk": None,
                          "why": why, "where": None})

    decisions.sort(key=lambda d: (d["action"], d["names"][0].lower()))
    return report, decisions


def _faces_block(decisions):
    rows = []
    for d in decisions:
        if d["action"] == "skip":
            continue
        latin = _q(d["latin"]) if d.get("latin") else "None"
        lo = "0x%04X" % d["lo"] if d.get("latin") else "0"
        hi = "0x%04X" % d["hi"] if d.get("latin") else "0"
        for name in d["names"]:
            rows.append("        (%s, %s, %s, %s)," % (_q(name), latin, lo, hi))
    return "\n".join(rows) if rows else "        # (nothing to alias)"


def _q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _table_comment(decisions):
    vf = {"keep-latin": "KEEP-LATIN", "keep-ascii": "KEEP-ASCII",
          "noto-only": "NOTO-ONLY", "skip": "SKIP"}
    lines = ["#", "# Decision table (from the .rpyc/.rpa scan of this game):"]
    for d in decisions:
        cjk = "" if d.get("cjk") is None else "cjk %5d  " % d["cjk"]
        where = d.get("where") or "-"
        names = ", ".join(d["names"])
        lines.append("#   %-11s %-36s %s%s" % (vf[d["action"]], names[:36], cjk, where))
        if len(names) > 36:
            lines.append("#   %-11s %s" % ("", names[36:]))
    return "\n".join(lines) + "\n"


def _code_only(text):
    """Drop comments and docstrings so a check sees code, not prose.

    The shim documents the very call signature being checked, so scanning raw
    text would flag its own explanatory comment.
    """
    text = re.sub(r'""".*?"""', '""', text, flags=re.S)
    return "\n".join(line.split("#", 1)[0] for line in text.splitlines())


def validate_shim(text):
    """Catch the failure mode that costs a startup crash.

    FontGroup.add takes (font, start, end); end has no default. A two-argument
    call raises TypeError at init 999, which the player sees as the game not
    starting at all. Counting arguments here is cheaper than discovering it in
    a playtest.
    """
    code = _code_only(text)
    problems = []
    for m in re.finditer(r"\.add\(([^()]*)\)", code):
        args = [a for a in m.group(1).split(",") if a.strip()]
        if len(args) < 3:
            problems.append("FontGroup.add called with %d argument(s): %s"
                            % (len(args), m.group(0)))
    if "config.font_name_map[" not in code:
        problems.append("no config.font_name_map assignment")
    if "FontGroup()" not in code:
        problems.append("no FontGroup constructed")

    # The body of `init 999 python:` is plain Python, so it can be compiled
    # here without booting the engine. Names like FontGroup and config are
    # undefined at this point, which is fine - compile() checks syntax only.
    # This is what catches a generated font name that broke its own quoting.
    problems.extend(_init_problems(text, "<zz_localization>"))
    return problems


def _init_problems(text, filename):
    """Compile-check the file's `init 999 python:` block. Both generated files
    put their one Python block there, so the extraction is shared."""
    body = []
    inside = False
    for line in text.splitlines():
        if line.startswith("init 999 python:"):
            inside = True
            continue
        if inside:
            if not line.strip():
                body.append("")
            elif line.startswith("    "):
                body.append(line[4:])
            else:
                break
    if not body:
        return ["no init 999 python: block found"]
    try:
        compile("\n".join(body), filename, "exec")
    except SyntaxError as e:
        return ["python block does not compile: line %s: %s" % (e.lineno, e.msg)]
    return []


def _label_body(text, name):
    """The statement lines of `label <name>:`, comments and blanks dropped.

    A line that starts at column zero ends the label, which is how the label's
    body is told apart from the next top-level statement.
    """
    out = []
    inside = False
    for line in text.splitlines():
        if not inside:
            if line.startswith("label %s:" % name):
                inside = True
            continue
        if line and not line[0].isspace():
            break
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append(stripped)
    return out


def validate_intro(text):
    """Catch the two ways the generated label override can break a game.

    An override that names a label the file does not define makes the engine
    jump to a label that is not there, which the player sees as the game not
    starting at all. A label body with anything beyond a bare `return` leaks the
    dynamic variables `_splashscreen` sets immediately before jumping here
    (renpy/common/00start.rpy), because only returning unwinds them.
    """
    code = _code_only(text)
    problems = []
    if 'config.label_overrides["splashscreen"]' not in code:
        problems.append("no config.label_overrides[\"splashscreen\"] assignment")
    if '"%s"' % INTRO_LABEL not in code:
        problems.append("nothing points at the label `%s`" % INTRO_LABEL)
    if "label %s:" % INTRO_LABEL not in code:
        problems.append("no `label %s:` defined" % INTRO_LABEL)

    problems.extend(_init_problems(text, "<zz_rpykit_intro>"))

    body = _label_body(text, INTRO_LABEL)
    if body != ["return"]:
        problems.append("`label %s:` must be exactly one `return`, found %r"
                        % (INTRO_LABEL, body))
    return problems


def _write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    tmp = path + ".part"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)


def _move_file(src, dst):
    """Move src onto dst, across volumes if need be.

    os.replace is the atomic choice but refuses a D: -> C: move, and the
    workspace lives under %LOCALAPPDATA% while games usually sit on another
    drive, so the copy-and-unlink fallback is the common path here, not the
    exception. An existing dst is cleared first: re-quarantining after the
    player put the file back must not raise.
    """
    d = os.path.dirname(dst)
    if d:
        os.makedirs(d, exist_ok=True)
    if os.path.exists(dst):
        os.remove(dst)
    shutil.move(src, dst)


def _quarantine_intro_conflicts(args, game_dir, work):
    """Move a rival splashscreen override aside so ours is the only one left.

    Only `zz`-prefixed add-ons are ever moved. Anything else that sets
    label_overrides is a script the game itself ships, and relocating a game's
    own file would break it far worse than the conflict it resolves - `init 999`
    already loads after any plain `init python:` block, so a warning is enough
    there. The move needs --force, which is what the window always passes.

    Both halves of the pair go: an orphaned .rpyc is still loaded by Ren'Py
    (renpy/script.py load_appropriate_file), so leaving it behind would keep the
    rival override live and make the quarantine look like it did nothing.
    """
    conflicts = find_intro_conflicts(game_dir)
    if not conflicts:
        return
    qdir = proj.ensure_dir(os.path.join(work, "quarantine"))
    for name in conflicts:
        if not args.force or not name.lower().startswith("zz"):
            print("[S6] note   : game/%s redirects the splashscreen too" % name)
            print("[S6]          ours loads last (init 999) so ours wins; left in place")
            continue
        if args.dry_run:
            print("[S6] dry-run: would quarantine game/%s (and its .rpyc if any)" % name)
            continue
        for rel in (name, name + "c"):
            src = os.path.join(game_dir, "game", rel)
            if not os.path.isfile(src):
                continue
            _move_file(src, os.path.join(qdir, rel))
            proj.record_quarantine(work, game_dir, "game/" + rel, rel,
                                   source=QUARANTINE_INTRO)
            print("[S6] quarantine: game/%s -> quarantine/%s" % (rel, rel))


def _remove_pair(game_dir, rel):
    """Delete a generated .rpy and the .rpyc Ren'Py compiled from it.

    Both halves or neither: Ren'Py loads a leftover .rpyc exactly as happily as
    a .rpy, so removing only the source leaves the change in place and makes
    --revert look like it did nothing. Every feature reverts through here so
    that none of them can forget the compiled half.
    """
    out = []
    for candidate in (rel, rel + "c"):
        full = os.path.join(game_dir, *candidate.split("/"))
        if os.path.isfile(full):
            os.remove(full)
            out.append(candidate)
    return out


def _guard_foreign(args, game_dir, work, targets):
    """Stop on a target path holding a file this tool cannot prove it wrote.

    `_is_ours` already covers the wiped-manifest case, so this only fires on a
    genuinely foreign file - the player's own hand-written shim. That must not
    be silently overwritten, hence --force, and even then it is copied aside
    rather than lost.
    """
    manifest = proj.load_manifest(work)
    ours = {e["path"] for e in manifest.get("files", [])}
    for rel in targets:
        full = os.path.join(game_dir, *rel.split("/"))
        if not os.path.exists(full) or rel in ours or _is_ours(full):
            continue
        if not args.force:
            # A preview reports the clash instead of dying on it, so the window's
            # 干跑预览 can still show what the install would decide.
            if args.dry_run:
                print("[S6] dry-run: %s is foreign; would refuse (pass --force)" % rel)
                continue
            raise FontFixError(
                "%s already exists and was not installed by rpykit-luna.\n"
                "  pass --force to quarantine the leftover and continue." % rel)
        if args.dry_run:
            print("[S6] dry-run: would quarantine %s -> quarantine/%s"
                  % (rel, os.path.basename(rel)))
            continue
        qdir = proj.ensure_dir(os.path.join(work, "quarantine"))
        shutil.copy2(full, os.path.join(qdir, os.path.basename(rel)))
        print("[S6] quarantine: %s -> quarantine/%s" % (rel, os.path.basename(rel)))


# --- the features themselves ----------------------------------------------
#
# prepare() builds this feature's file, checks it, and says what it would do;
# apply() is the only thing that writes. run() prepares every selected feature
# before applying any of them, so a self-check failure in the last one cannot
# leave the first one's files on disk.

def _font_targets(game_dir):
    return ["game/" + SHIM_REL, "game/" + GAME_FONT_REL]


def _prepare_font(args, game_dir, work, ctx):
    decisions = ctx["decisions"]
    aliased = [d for d in decisions if d["action"] != "skip"]
    lang_block = ""
    if args.mode == "full":
        lang_block = string.Template(LANGUAGE_BLOCK).substitute(lang=args.lang)

    text = SHIM.substitute(
        stamp=ctx["stamp"], game_dir=game_dir, mode=args.mode,
        cjk_path=GAME_FONT_REL, faces=_faces_block(decisions),
        language_block=lang_block, table_comment=_table_comment(decisions))

    if args.dry_run:
        if aliased:
            print("[S6] dry-run: would write game/%s (%.1f MB)"
                  % (GAME_FONT_REL, os.path.getsize(ASSET_FONT) / 1e6))
        print("[S6] dry-run: would write game/%s (%d lines, self-check clean)"
              % (SHIM_REL, text.count("\n")))

    def apply():
        # The font is 17.8 MB, so it is only copied when something will actually
        # reference it. The shim is written either way - it is what
        # installed_state reads to tell "rpykit was here" from "not installed".
        if aliased:
            font_path = os.path.join(game_dir, "game", *GAME_FONT_REL.split("/"))
            os.makedirs(os.path.dirname(font_path), exist_ok=True)
            shutil.copy2(ASSET_FONT, font_path)
            proj.record_file(work, game_dir, "game/" + GAME_FONT_REL,
                             "fontfix:cjk-font")
            print("[S6] wrote  : game/%s (%.1f MB)"
                  % (GAME_FONT_REL, os.path.getsize(font_path) / 1e6))
        _write(os.path.join(game_dir, "game", SHIM_REL), text)
        proj.record_file(work, game_dir, "game/" + SHIM_REL, "fontfix:shim")
        n_alias = sum(len(d["names"]) for d in aliased)
        n_groups = len({(d.get("latin"), d.get("lo"), d.get("hi"))
                        for d in aliased})
        print("[S6] wrote  : game/%s (%d aliases over %d FontGroup(s), "
              "self-check clean)" % (SHIM_REL, n_alias, n_groups))

    return {"problems": validate_shim(text), "apply": apply}


def _revert_font(game_dir, work, manifest):
    removed = _remove_pair(game_dir, "game/" + SHIM_REL)
    removed += _remove_pair(game_dir, "game/" + GAME_FONT_REL)
    # Only this feature creates game/localization/, so only this feature tidies
    # it away - and only when nothing else has since put something in it.
    locdir = os.path.join(game_dir, "game", "localization")
    if os.path.isdir(locdir) and not os.listdir(locdir):
        os.rmdir(locdir)
        removed.append("game/localization/")
    return removed, []


def _intro_targets(game_dir):
    return ["game/" + INTRO_REL]


def _prepare_intro(args, game_dir, work, ctx):
    text = INTRO.substitute(stamp=ctx["stamp"], game_dir=game_dir,
                            intro_label=INTRO_LABEL)

    if args.dry_run:
        print("[S6] dry-run: would write game/%s (opening logos skipped, "
              "self-check clean)" % INTRO_REL)

    def apply():
        # The rival has to move before ours lands, or two files would briefly
        # both claim the splashscreen.
        _quarantine_intro_conflicts(args, game_dir, work)
        _write(os.path.join(game_dir, "game", INTRO_REL), text)
        proj.record_file(work, game_dir, "game/" + INTRO_REL, "fontfix:intro")
        print("[S6] wrote  : game/%s (opening logos skipped, self-check clean)"
              % INTRO_REL)

    return {"problems": validate_intro(text), "apply": apply}


def _revert_intro(game_dir, work, manifest):
    removed = _remove_pair(game_dir, "game/" + INTRO_REL)
    return removed, _restore_intro_quarantine(game_dir, work, manifest)


class _Feature(object):
    """One installable behaviour, and the questions the runner asks of it.

    Deliberately not a class hierarchy. The tool has two features and might
    have three, so what matters is that run() never names one - not that they
    share an ancestor. Adding a fourth kind of change means a catalogue entry
    in features.py, a prepare/revert pair here and an entry in _FEATURES; the
    window, the parser and the runner all pick it up on their own.
    """

    def __init__(self, fid, state, targets, prepare, revert):
        self.id = fid
        self.state = state
        self.targets = targets
        self.prepare = prepare
        self.revert = revert


_FEATURES = {
    "fontfix": _Feature("fontfix", _font_state, _font_targets,
                        _prepare_font, _revert_font),
    "intro": _Feature("intro", _intro_state, _intro_targets,
                      _prepare_intro, _revert_intro),
}


def install(args, game_dir, work, ctx):
    """Run every selected feature, once every one of them has passed its check."""
    selected = features.selected(args)
    targets = []
    for fid in selected:
        targets += _FEATURES[fid].targets(game_dir)
    _guard_foreign(args, game_dir, work, targets)

    plans, problems = [], []
    for fid in selected:
        plan = _FEATURES[fid].prepare(args, game_dir, work, ctx)
        problems += plan["problems"]
        plans.append(plan)
    if problems:
        for p in problems:
            print("[S6] !! %s" % p)
        raise FontFixError("generated files failed self-check; nothing written")
    if args.dry_run:
        return
    for plan in plans:
        plan["apply"]()


def _restore_intro_quarantine(game_dir, work, manifest):
    """Put a rival override quarantined by install() back where it was.

    Anything without `source == QUARANTINE_INTRO` is left alone: init sweeps
    leftovers away for good, and only this feature promises the file back.
    """
    qdir = os.path.join(work, "quarantine")
    kept, restored = [], []
    for e in manifest.get("quarantined", []):
        if e.get("source") != QUARANTINE_INTRO:
            kept.append(e)
            continue
        stored = e.get("stored_as") or ""
        src = os.path.join(qdir, stored)
        dest = os.path.join(game_dir, *e.get("path", "").split("/"))
        if not os.path.isfile(src):
            continue
        if os.path.exists(dest):
            print("[S6] note   : %s is already back; copy kept at quarantine/%s"
                  % (e["path"], stored))
            continue
        _move_file(src, dest)
        restored.append(e["path"])
    manifest["quarantined"] = kept
    return restored


def revert(game_dir, work):
    manifest = proj.load_manifest(work)

    # Every feature, not just the selected ones: one run may have installed the
    # fonts and a later one may have ticked only the intro, and --revert is the
    # single command that has to undo all of it.
    removed, restored = [], []
    for fid in features.ids():
        feat_removed, feat_restored = _FEATURES[fid].revert(game_dir, work, manifest)
        removed += feat_removed
        restored += feat_restored

    manifest["files"] = [e for e in manifest.get("files", [])
                         if not e.get("source", "").startswith("fontfix:")]
    proj.save_manifest(work, manifest)

    for rel in removed:
        print("[S6] removed: %s" % rel)
    for rel in restored:
        print("[S6] restored: %s" % rel)
    if not removed:
        print("[S6] nothing to remove")
    print("[S6] reverted")


def run(args):
    if args.game_dir:
        game_dir = os.path.abspath(args.game_dir)
    else:
        from_proj = proj.load_project(args.work)
        game_dir = from_proj["game_dir"]
    if not os.path.isdir(os.path.join(game_dir, "game")):
        raise SystemExit("no game/ subdir - is this a Ren'Py distribution? %s" % game_dir)

    work = proj.ensure_dir(args.work or proj.work_dir_for(game_dir))

    print("[S6] game   : %s" % game_dir)
    if args.revert:
        revert(game_dir, work)
        return 0

    if args.mode not in ("luna", "full"):
        raise SystemExit("--mode must be luna or full")

    selected = features.selected(args)

    # Before anything is decided, say what this game is. The folder alone
    # answers it, and the answer changes what the player should expect: a py2
    # build is an untested path, and a fully packed one hides the fonts we are
    # supposed to be aliasing.
    survey = compat.survey(game_dir)
    print("[S6] compat : %s" % compat.summary(survey))
    for reason in survey["reasons"]:
        print("[S6]          %s" % reason)
    if survey["verdict"] == "bad":
        raise SystemExit("not a Ren'Py distribution: %s" % game_dir)

    print("[S6] work   : %s" % work)
    print("[S6] mode   : %s%s" % (
        args.mode,
        " - fonts only; language and tl/ untouched (for runtime text injection)"
        if args.mode == "luna" else " - fonts + config.language"))
    print("[S6] features: %s" % "   ".join(
        "%s %s" % ("+" if fid in selected else "-", features.title_of(fid))
        for fid in features.ids()))

    before = installed_state(game_dir)
    if before["ours"]:
        print("[S6] state  : already installed (mode %s, %s); overwriting in place"
              % (before["mode"] or "?", "current template" if before["current"]
                 else "OLDER template"))

    report, decisions = analyse(game_dir)

    n_refs = len(report["refs"])
    print("[S6] scan   : %d font reference(s) in scripts, %d font file(s) shipped"
          % (n_refs, len(report["inventory"])))
    print("[S6] faces  :")
    for d in decisions:
        cjk = "--" if d.get("cjk") is None else "%d" % d["cjk"]
        names = ", ".join(d["names"])
        print("      %-11s %-38s cjk %5s  %s"
              % (d["action"], names[:38], cjk, d["why"]))

    aliased = [d for d in decisions if d["action"] != "skip"]
    if not aliased and "fontfix" in selected:
        print("[S6] fonts  : every face already covers Chinese; nothing to alias")

    # The intro is worth installing on its own, so a game whose faces all
    # already cover Chinese still gets this far instead of bailing out. Bail
    # only when no selected feature has anything left to do.
    if not (aliased and "fontfix" in selected) and "intro" not in selected:
        print("[S6] every face already covers Chinese; nothing to do")
        return 0

    ctx = {"report": report, "decisions": decisions, "survey": survey,
           "stamp": datetime.datetime.now().isoformat(timespec="seconds")}
    install(args, game_dir, work, ctx)

    proj.write_json(os.path.join(work, "fontfix_report.json"), {
        "game_dir": game_dir,
        "mode": args.mode,
        "installed": not args.dry_run,
        "cjk_font": GAME_FONT_REL,
        "shim": "game/" + SHIM_REL,
        "intro": "game/" + INTRO_REL if "intro" in selected else None,
        "features": selected,
        "skip_intro": "intro" in selected,
        "compat": survey,
        "decisions": decisions,
        "refs": report["refs"],
    })

    print("[S6] OK - start the game to verify; `rpykit-luna --revert` undoes it")
    return 0
