"""Font reconnaissance: which fonts does a game reference, and where do they live?

A font name only reaches a renderer two ways - as a string literal in a game
script, or as the name of a font file shipped alongside it. This module finds
both, reading .rpyc containers straight out of the game directory *and* out of
the .rpa archives, so it works on a fresh game that has never been unpacked.

It deliberately does not unpickle the AST. A regex over the decompressed
payload is enough to recover font literals, and it sidesteps the whole
"bundled Python 3.9 vs system Python 3.13" minefield that engine.load_script
has to negotiate.
"""

import os
import re
import struct
import zlib

import rpa

RPYC2_HEADER = b"RENPY RPC2"
FONT_EXTS = (".ttf", ".otf", ".ttc", ".otc")

# The shim `rpykit fontfix` installs. It is not part of the game, but it names
# a font in its code and lists every face the game uses in a header comment -
# so scanning it feeds those names back in as though the game had referenced
# them, and each reinstall invents another generation of aliases such as
# "localization/NotoSansSC-VF.ttf". Skipped only when it carries the marker,
# so a same-named file from somewhere else is still read (and `install()`
# refuses to overwrite that one anyway).
GENERATED_SHIM = "zz_localization.rpy"
GENERATED_MARKER = b"GENERATED BY `rpykit fontfix`"


def _is_generated_shim(name, path=None, blob=None):
    """True for the shim rpykit wrote, in either of its compiled forms.

    Ren'Py drops comments when it compiles, so the marker only survives in the
    .rpy; the .rpyc is therefore identified by its sibling rather than by
    itself.
    """
    low = name.lower()
    if low == GENERATED_SHIM:
        if blob is not None:
            return GENERATED_MARKER in blob[:2048]
        try:
            with open(path, "rb") as f:
                return GENERATED_MARKER in f.read(2048)
        except OSError:
            return False
    if low == GENERATED_SHIM + "c" and path:
        sibling = path[:-1]
        return os.path.isfile(sibling) and _is_generated_shim(GENERATED_SHIM, sibling)
    return False

# Printable-ASCII runs. Font names are ASCII, and pickled payloads interleave
# them with binary length prefixes and non-printable opcodes, so a run is the
# natural unit to search.
_ASCII_RUN = re.compile(rb"[\x20-\x7e]{3,}")

# Filename characters. Notably absent: = { } " < > so that `{font=tycho.ttf}`
# yields `tycho.ttf` and not the surrounding markup, and `=` itself so the
# match cannot start on the `font` keyword.
_REF = re.compile(
    rb"(?i)(?<![A-Za-z0-9_.\-])"
    rb"([A-Za-z0-9_][A-Za-z0-9_\-/\\ .]{0,80}?\.(?:ttf|otf|ttc|otc))"
)


def _multi_inflate(blob):
    """Yield each zlib stream in a run of concatenated streams."""
    pos = 0
    while pos < len(blob):
        d = zlib.decompressobj()
        try:
            out = d.decompress(blob[pos:])
        except zlib.error:
            return
        if not out:
            return
        yield out
        if not d.unused_data:
            return
        pos = len(blob) - len(d.unused_data)


def payloads(blob):
    """Yield the decompressed payloads of a .rpyc blob (or a loose .rpy source).

    `blob` is bytes from a file on disk or from an .rpa entry, so both paths
    go through the same parser. Every slot is read, not just slot 2: slot 1
    holds the pre-restructure AST and may carry literals no longer present
    after the static transforms that create Translate nodes.
    """
    if not blob.startswith(RPYC2_HEADER):
        try:
            yield zlib.decompress(blob)
        except zlib.error:
            yield blob
        return

    off = len(RPYC2_HEADER)
    while off + 12 <= len(blob):
        idx, start, length = struct.unpack("III", blob[off:off + 12])
        off += 12
        if idx == 0:
            break
        if start + length > len(blob):
            break
        got = False
        for piece in _multi_inflate(blob[start:start + length]):
            got = True
            yield piece
        if not got:
            yield blob[start:start + length]


def refs_in(blob):
    """Font references appearing in one .rpyc/.rpy blob."""
    found = set()
    for piece in payloads(blob):
        for run in _ASCII_RUN.finditer(piece):
            for m in _REF.finditer(run.group()):
                name = m.group(1).decode("ascii", "replace").strip(" .")
                if name and name.lower().endswith(FONT_EXTS):
                    found.add(name)
    return found


def basename(ref):
    return ref.replace("\\", "/").rsplit("/", 1)[-1]


# --- sources ---------------------------------------------------------------

def script_blobs(game_dir, archive_paths):
    """Yield (label, bytes) for every script the game ships.

    Loose .rpy/.rpyc in game/ come first, then whatever is packed in the
    archives. Labels are stable and human-readable so the report can point at
    where a font reference was seen.
    """
    gdir = os.path.join(game_dir, "game")
    if os.path.isdir(gdir):
        for name in sorted(os.listdir(gdir)):
            low = name.lower()
            if not low.endswith((".rpyc", ".rpy")):
                continue
            full = os.path.join(gdir, name)
            if not os.path.isfile(full):
                continue
            try:
                with open(full, "rb") as f:
                    blob = f.read()
            except OSError:
                continue
            if _is_generated_shim(name, full, blob):
                continue
            yield name, blob

    for apath in archive_paths:
        try:
            index = rpa.load_index(apath)
        except rpa.RpaError:
            continue
        aname = os.path.basename(apath)
        for entry in sorted(index):
            if not entry.lower().endswith((".rpyc", ".rpy")):
                continue
            try:
                blob = rpa.read_entry(apath, index[entry])
            except rpa.RpaError:
                continue
            if _is_generated_shim(basename(entry), blob=blob):
                continue
            yield "%s:%s" % (aname, entry), blob


def font_inventory(game_dir, archive_paths):
    """{file name: {'where': ..., 'kind': 'loose'|'rpa', ...}} for shipped fonts.

    Keyed by basename so that a reference of `fonts/tycho.ttf` matches an
    entry named `game/fonts/tycho.ttf` without the caller knowing the layout.
    """
    out = {}
    gdir = os.path.join(game_dir, "game")

    if os.path.isdir(gdir):
        for root, dirs, files in os.walk(gdir):
            dirs[:] = [d for d in dirs if d not in ("cache", "saves")]
            for fn in files:
                if fn.lower().endswith(FONT_EXTS):
                    out.setdefault(fn, {
                        "where": "loose",
                        "path": os.path.join(root, fn),
                    })

    for apath in archive_paths:
        try:
            index = rpa.load_index(apath)
        except rpa.RpaError:
            continue
        for entry in sorted(index):
            if entry.lower().endswith(FONT_EXTS):
                out.setdefault(basename(entry), {
                    "where": "rpa",
                    "archive": apath,
                    "entry": entry,
                })

    # Ren'Py's own faces live outside game/, and DejaVuSans is the stock
    # default in every gui.rpy, so it is missing from most inventories.
    common = os.path.join(game_dir, "renpy", "common")
    if os.path.isdir(common):
        for root, dirs, files in os.walk(common):
            for fn in files:
                if fn.lower().endswith(FONT_EXTS):
                    out.setdefault(fn, {
                        "where": "renpy-common",
                        "path": os.path.join(root, fn),
                    })
    return out


def font_bytes(entry):
    """Raw bytes of an inventory entry, or None if it cannot be read."""
    try:
        if entry["where"] == "rpa":
            index = rpa.load_index(entry["archive"])
            for name, e in index.items():
                if basename(name) == basename(entry["entry"]):
                    return rpa.read_entry(entry["archive"], e)
            return None
        with open(entry["path"], "rb") as f:
            return f.read()
    except (OSError, rpa.RpaError):
        return None


def recon(game_dir, archive_paths):
    """Full font picture for one game.

    Returns a dict with:
      refs      - reference -> sorted list of scripts naming it
      inventory - file name -> where that font file can be read from
    """
    refs = {}
    for label, blob in script_blobs(game_dir, archive_paths):
        for name in refs_in(blob):
            refs.setdefault(name, set()).add(label)
    return {
        "refs": {k: sorted(v) for k, v in sorted(refs.items())},
        "inventory": font_inventory(game_dir, archive_paths),
    }
